[package]
name = "newbo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.42"
gl33 = "0.2.1"
glfw = "0.45.0"
rand = "0.8.5"
downcast-rs = "1.2.0"
image = "0.24.5"
